### PR TITLE
ES-55 installation fix

### PR DESCRIPTION
**Pull request by pivnicek**
Need to make this change in order that it can be properly used by the sandbox

### CODE REVIEW

**Comment by pepamartinec** [comment]
Can you describe a bit what the change does? As always, it's some mambo jumbo for me :smile:

**Comment by odinuv** [comment]
Doesn't make much sense for me either - by breifly reading https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#using-find-or-find-packages - we should either use src-layout or flat-layout, which require no configuration, if not then custom discover fixes it, but then it requires source dir, which would be src, so why exclude tests ?

**Comment by pivnicek** [comment]
ok @odinuv and @pepamartinec thanks for that, I've updated it and it seems to work this way too.

**Review by odinuv — APPROVED** [review]
this should work I think, but I haven't tried it

**Pull request merged**
